---
- name: Install packages
  hosts: k8s_cluster

  roles:
    - prepare-hosts

- name: Install Control nodes
  hosts: k8s_masters

  roles:
    - master

- name: Install worker nodes
  hosts: "{{ groups['k8s_masters'][0] }},k8s_workers"

  roles:
    - workers
