---

- name: Check for installed tigera-operator
  ansible.builtin.command: kubectl get ns tigera-operator
  register: tigera_operator_out
  ignore_errors: true

- name: Install tigera CRD
  when: tigera_operator_out.rc == 1
  ansible.builtin.shell: "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/{{ tigera_version }}/manifests/operator-crds.yaml"

- name: Install tigera-operator
  when: tigera_operator_out.rc == 1
  ansible.builtin.shell: "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/{{ tigera_version }}/manifests/tigera-operator.yaml"


- name: Copy calico-install.yaml
  ansible.builtin.template:
    src: calico-install.j2
    dest: /etc/kubernetes/calico-install.yaml


- name: Install Calico
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/calico-install.yaml
