---

- name: Check if kubeadm has already run
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: End play
  ansible.builtin.meta: end_play
  when: kubeadm_ca.stat.exists

- name: Create /etc/kubernetes directory
  ansible.builtin.file:
    path: /etc/kubernetes
    state: directory
    mode: '700'


- name: Copy kubeadm-config.yaml
  ansible.builtin.template:
    src: kubeadm-config.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0600'

- name: Init control node
  ansible.builtin.command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml

- name: Install Utils
  ansible.builtin.include_tasks: utils.yml

- name: Install Calico
  ansible.builtin.include_tasks: calico.yml

- name: Setup DNS
  ansible.builtin.include_tasks: dns.yml
