---

- name: Install containerd
  ansible.builtin.apt:
    name: containerd

- name: Ensure /etc/containerd exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Create containerd config.toml
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

- name: Configuring cgroup [config.toml]
  ansible.builtin.shell: sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml

- name: Change Sandbox Image [config.toml]
  when: snadbox_image is defined
  ansible.builtin.shell: |
    sed -i 's|sandbox_image = ".*"|sandbox_image = "{{ sandbox_image }}"|' /etc/containerd/config.toml

- name: Enable the containerd service and start service
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true

